config/routes.rb
Rails.application.routes.draw do
  get "/search_address" , to: 'users#search_address'
  resources :users
  get '/search_user', to: 'users#search_user'
 end

app/models/address.rb
class Address < ApplicationRecord
    validates :city, presence: true
    validates :state, presence: true
    validates :country, presence: true
    validates :pin_code, presence: true
    validates :district, presence: true
    
    belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord

    VALID_EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i

    validates :email, presence: true,
            length: {minimum: 5, maxmimum: 105},
            uniqueness: {case_sensitive: false},
            format: { with: VALID_EMAIL_REGEX }

 
  validates :phone, numericality: { only_integer: true }
  validates :name, presence: true
          
has_many :address ,  dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users 
  def index
    @users = User.all
  end

  # GET /users/1 
  def show
  end

  # GET /users/new
  def new
    @user = User.new
    @address = Address.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users 

  def create
    @user = User.new(user_params)
    respond_to do |format|
     
      if @user.save
        @address = Address.create({
                city: params[:user][:address][:city] ,
                country: params[:user][:address][:country] ,
                pin_code: params[:user][:address][:pin_code] ,
                state: params[:user][:address][:state] ,
                district: params[:user][:address][:district] ,
                user_id: @user.id 
              })

        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def search_address
  
    @address = Address.where("city LIKE ? OR country LIKE ? OR district LIKE ? OR state LIKE ? ", "%#{params[:address]}%","%#{params[:address]}%","%#{params[:address]}%","%#{params[:address]}%" )
    
    respond_to do |format|
      format.js 
      format.html 
    end
  end


  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :phone , :address => [])
    end

    def address_params
      params.require(:user).permit(:address)
    end 

   

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
     <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
     <script type="text/javascript" src="https://code.jquery.com/jquery-1.7.1.min.js"></script>
  </head>

  <body>
    <%= yield %>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_show_address.html.erb
<% if @address.empty?%>
 <h4> No record found </h4>
 <%else%>
 <table class="table table-border">
 <thead>
 <tr>
 <th>Name</th>
 <th>city</th>
 <th>District</th>
 <th>state</th>
 <th>country</th>
 </tr>
 </thead>
 <tbody>
 
 <% @address.each  do |address| %>
<tr>
 <td><%= address.user.name%></td>
 <td><%= highlight(address.city, params[:address])%></td>
 <td><%= highlight(address.district, params[:address]) %></td>
 <td><%= highlight(address.state , params[:address]) %></td>
 <td><%= highlight(address.country , params[:address]) %></td>
 </tr>

 <%end%>
 <%end%>
 </tbody>

app/views/users/address_count2.html.erb
<div class="container mt-5 border p-5">
<% if @address_count > 0 %>
<h4>  users from indore is : <%= @address_count%> </h4> 

<table class="table">
        <thead>
          <tr>
            <th>Name</th>
            <th>Phone</th>
            <th>Email</th>
             <th>City</th>
            <th>Country</th>
         
            
          </tr>
       </thead>
     <tbody>

        <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td><%= user.phone %></td>
          <% @address = Address.find_by_user_id(user.id)%>
          
                <td><%= @address.city %></td> 
                <td><%= @address.state %> </td>
           </tr>
        <% end %>
      </tbody>

      <%else %>
<%= "their has been no user from this city" %>
<%end%>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>
 <h1>Users</h1>
 <%= link_to 'New User', new_user_path  , class:"btn btn-outline-primary"%>
 <br><br>

  <div class="row">
    <div class="col-md-6">
      <table class="table">
        <thead>
          <tr>
            <th>Name</th>
            <th>Phone</th>
            <th>Email</th>
             <th>City</th>
            <th>Country</th>
            <th>Phone</th>
            <th colspan="3"></th>
          </tr>
       </thead>
      <tbody>

        <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td><%= user.phone %></td>
          <% @address = Address.find_by_user_id(user.id)%>

                <td><%= @address.city %></td> 
                <td><%= @address.state %> </td>
            
          <td><%= link_to 'Show', user %></td>
          <td><%= link_to 'Edit', edit_user_path(user) %></td>
          <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
      </tbody>
</table>

<br>

<%# <%= link_to 'search user by address', address_count_path , class:"btn btn-outline-primary" %> 

    <h5>Search address </h5>
    <input type = "text" name = "search" id = "search" class="form-control"  onkeyup = "search_user(id)" placeholder = "Enter city , country , district" >

  <div id = "result_dev">
   <%# resulted values are show will be here %>
  </div>

</div>


<script type="text/javascript">
    function search_user(){
      var query = document.getElementById("search").value
      console.log(query);
      if (query) {
        $("#result_dev").show()
       $.ajax({
        url: "<%= search_address_path %>",
        data: {'address': query}
      })
      } else {  
        $("#result_dev").hide()
        
      }
      
    }

</script>

app/views/users/new.html.erb
<h1>New User</h1>

<%# <%= render 'form', user: @user %> 
<%= form_for @user, url: {action: "create"} do |form| %>
<% if @user.errors.any? || %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% @user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

   <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

   <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

<%= form.fields_for @address do |c| %>

 <div class="field">
    <%= label_tag("Pin_code") %>
    <%= c.text_field(:pin_code) %>
  </div>

 <div class="field">
    <%= label_tag("City") %>
    <%= c.text_field(:city) %>
  </div>
<div class="field">
    <%= label_tag("State") %>
    <%= c.text_field(:state) %>
  </div>
  <div class="field">
    <%= label_tag("Country") %>
    <%= c.text_field(:country) %>
  </div>
  <div class="field">
    <%= label_tag("District") %>
    <%= c.text_field(:district) %>
  </div>
  <div class="field">
    <%= label_tag("House no") %>
    <%= c.text_field(:house_no) %>
  </div>

<% end %>
<br>
<%= form.submit("submit") %>
<% end %>

<%= link_to 'Back', users_path %>

app/views/users/search_address.js.erb
$('#result_dev').html("<%= j (render 'show_address')%>");

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @user.phone %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>